version: "3.8"

services:
  chaind:
    image: wealdtech/chaind:latest
    restart: unless-stopped
    networks:
      - chaind
    volumes:
      - ./chaind.config.docker-compose.yml:/app/chaind.yml:ro
    command: --base-dir /app
    environment:
      &environment
      CHAIND_CHAINDB_URL: postgres://chaind:chaind@db:5432
      CHAIND_ETH2CLIENT_ADDRESS: ${CHAIND_ETH2CLIENT_ADDRESS:-http://localhost:5051/}

  db:
    image: "postgres:14.2-bullseye"
    networks:
      - chaind
    restart: unless-stopped
    ports:
      - "127.0.0.1:5434:5432"
    environment:
      POSTGRES_USER: chaind
      POSTGRES_PASSWORD: chaind
      POSTGRES_DB: chaind
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  chaind:
    driver: bridge

volumes:
  db_data:
